remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Recipes & Rating Regressor Model
description: An indivdiual project that builds a regressor model based on data from Food.com, submitted as an assignment for DSC 80 at UCSD.
